var $LRIC={util:{}};
(function(e){e.elementById=function(e){return document.getElementById(e)};e.elementsByClass=function(e,a){a=a||document.body;for(var b=[],c=new RegExp("(^| )"+e+"( |$)"),d=a.getElementsByTagName("*"),g=0,f=d.length;g<f;g++)c.test(d[g].className)&&b.push(d[g]);return b};e.addEvent=function(e,a,b){var c=[];a instanceof Array?c=a:c.push(a);for(a=0;a<c.length;a++)c[a]["on"+e]=b};var f={};e.tmpl=function a(b,c){var d=/\W/.test(b)?new Function("obj","var p=[],print=function(){p.push.apply(p,arguments);};with(obj){p.push('"+b.replace(/[\r\t\n]/g,
" ").split("<%").join("\t").replace(/((^|%>)[^\t]*)'/g,"$1\r").replace(/\t=(.*?)%>/g,"',$1,'").split("\t").join("');").split("%>").join("p.push('").split("\r").join("\\'")+"');}return p.join('');"):f[b]=f[b]||a(e.elementById(b).innerHTML);return c?d(c):d};e.hashTmpl=function(a,b){var c=/\W/.test(a)?new Function("obj","var p=[],print=function(){p.push.apply(p,arguments);};with(obj){p.push('"+a.replace(/[\r\t\n]/g," ").split("<#").join("\t").replace(/((^|#>)[^\t]*)'/g,"$1\r").replace(/\t=(.*?)#>/g,
"',$1,'").split("\t").join("');").split("#>").join("p.push('").split("\r").join("\\'")+"');}return p.join('');"):f[a]=f[a]||tmpl($LRIC.util.elementById(a).innerHTML);return b?c(b):c};e.openWindow=function(a){a=a||this.href;window.open(a,"lrpopupchildwindow","menubar=1,resizable=1,width=450,height=500");return!1};e.addCss=function(a,b){for(var c in b)a.style[c].cssText+=b[c];return!0};e.getPos=function(a){for(var b=0,c=0;null!=a;b+=a.offsetLeft,c+=a.offsetTop,a=a.offsetParent);return{x:b,y:c}};e.containsStringArray=
function(a,b){for(var c=0;c<a.length;c++)if(-1!==a[c].indexOf(b))return!0;return!1};e.addExternalCss=function(a,b){b=b||document;var c=b.getElementsByTagName("head")[0],d=b.createElement("link");d.rel="stylesheet";d.type="text/css";d.media="all";d.href=a;c.appendChild(d);return!0};e.addEmbedCss=function(a,b){b=b||document;var c=b.createElement("style");c.type="text/css";c.styleSheet?c.styleSheet.cssText=a:c.appendChild(document.createTextNode(a));b.getElementsByTagName("head")[0].appendChild(c);return!0};
e.addJs=function(a,b){b=b||document;var c=b.getElementsByTagName("head")[0],d=b.createElement("script");d.src=a;d.type="text/javascript";c.appendChild(d);return d};e.jsonpCall=function(a,b){if(window.loginRadiusAppJsonLoaded){var c=window.loginRadiusAppJsonLoaded;window.loginRadiusAppJsonLoaded=function(a){b(a);c(a)}}else window.loginRadiusAppJsonLoaded=b;var d=-1!=a.indexOf("?")?a+"&callback=loginRadiusAppJsonLoaded":a+"?callback=loginRadiusAppJsonLoaded";e.addJs(d)};e.arrayIndexOf=function(a,b,
c){c=c||0;for(var d=a.length;c<d;){if(a[c]===b)return c;++c}return-1};e.arrayRemove=function(a){for(var b,c=arguments,d=c.length,f;d&&a.length;)for(b=c[--d];-1!=(f=e.arrayIndexOf(a,b));)a.splice(f,1);return this};e.arrayContains=function(a,b,c){for(var d=a.length;d--;)if(c){if(a[d].toUpperCase()===b.toUpperCase())return!0}else if(a[d]===b)return!0;return!1};e.objectToArray=function(a){var b=[],c;for(c in a)a.hasOwnProperty(c)&&b.push(a[c]);return b};e.hasClass=function(a,b){return a.className.match(new RegExp("(\\s|^)"+
b+"(\\s|$)"))};e.addclass=function(a,b){if(!e.hasClass(a,b))return a.className+=" "+b,!0};e.removeclass=function(a,b){if(e.hasClass(a,b))return a.className=a.className.replace(new RegExp("(\\s|^)"+b+"(\\s|$)")," "),!0};e.isInt=function(a){return"number"===typeof a&&parseFloat(a)==parseInt(a,10)&&!isNaN(a)}})($LRIC.util);
(function(e){function f(){if(!g&&(g=!0,k)){for(var a=0;a<k.length;a++)k[a].call(window,[]);k=[]}}function h(a){var b=window.onload;window.onload="function"!=typeof window.onload?a:function(){b&&b();a()}}function a(){if(!d){d=!0;document.addEventListener&&!c.opera&&document.addEventListener("DOMContentLoaded",f,!1);c.msie&&window==top&&function(){if(!g){try{document.documentElement.doScroll("left")}catch(a){setTimeout(arguments.callee,0);return}f()}}();c.opera&&document.addEventListener("DOMContentLoaded",
function(){if(!g){for(var a=0;a<document.styleSheets.length;a++)if(document.styleSheets[a].disabled){setTimeout(arguments.callee,0);return}f()}},!1);if(c.safari){var a;(function(){if(!g)if("loaded"!=document.readyState&&"complete"!=document.readyState)setTimeout(arguments.callee,0);else{if(void 0===a){for(var b=document.getElementsByTagName("link"),c=0;c<b.length;c++)"stylesheet"==b[c].getAttribute("rel")&&a++;b=document.getElementsByTagName("style");a+=b.length}document.styleSheets.length!=a?setTimeout(arguments.callee,
0):f()}})()}h(f)}}var b=navigator.userAgent.toLowerCase(),c={version:(b.match(/.+(?:rv|it|ra|ie)[\/: ]([\d.]+)/)||[])[1],safari:/webkit/.test(b),opera:/opera/.test(b),msie:/msie/.test(b)&&!/opera/.test(b),mozilla:/mozilla/.test(b)&&!/(compatible|webkit)/.test(b)};e.browser=c;var d=!1,g=!1,k=[];e.ready=function(b,c){a();g?b.call(window,[]):k.push(function(){return b.call(window,[])})};a()})($LRIC.util);
$LRIC.renderInterface=function(e,f){$LRIC.util.jsonpCall("//cdn.loginradius.com/interface/json/"+f.apikey+".json",function(h){for(var a=f.hashTemplate?$LRIC.util.hashTmpl:$LRIC.util.tmpl,b=f.providerlist,c="",d=0;d<h.Providers.length;d++)if(void 0!==b){if(-1!=b.indexOf(h.Providers[d].Name))var g=h.Providers[d],c=c+a(f.templatename,g)}else g=h.Providers[d],c+=a(f.templatename,g);h=$LRIC.util.elementsByClass(e);for(d=0;d<h.length;d++)h[d].innerHTML=c})};